### ISSUE TITLE
Diagnostic text on settings is not readable

### ISSUE THREAD

**Issue by 0xDones** [elGusto/night-owlz#1]
### Description

When using the theme `night owl no italics`, the Diagnostic modal is not readable with this yellow background, as you can see in the screenshot below. Can we change it?

![image](https://github.com/elGusto/night-owlz/assets/29067941/c78a9221-f4dd-4022-9656-b2e32642bf7f)

**Comment by elGusto** [comment]
Updated the colors to be more readable in dark mode.  Please open another issue if you need to have more contrast.

**Comment by 0xDones** [comment]
Thanks @elGusto , much better now 😅
